### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by kevinspasiuk** [M-Picco/TP2-AlgosIII#1]
Modalidad de elección de personajes, grupos pre-establecidos o a elección del jugador?

**Comment by Titolasanta** [comment]
ya preguntaste kevin o le mando la pregunta a fede?

**Comment by kevinspasiuk** [comment]
No le pregunté!!

**Comment by edjus** [comment]
creo que eso depende de cada grupo, igual por ahora podemos hacer como que escoge un grupo ya prestablecido

**Comment by kevinspasiuk** [comment]
si mantenemos la abstracción se podría hacer ambos casos. Me estuve fijando tu complementación y si hacemos como grupos preestablecidos no va a ser difícil pasarlos grupos a elección. Propongo dejarlos preestablecidos ahora y después hacemos refactor si es necesario.

**Comment by M-Picco** [comment]
Grupos pre-establecidos:
 * Guerreros Z (Gohan, Goku, Piccolo)
 * Enemigos de la Tierra (Freezer, Majin Boo, Cell)
