### ISSUE TITLE
Falta para la entrega final

### ISSUE THREAD

**Issue by edjus** [M-Picco/TP2-AlgosIII#11]
Algunas cosas que nos faltan

- [x] Mostrar en la consola cuando un personaje consume un consumible

- [ ] Centrar el tablero

- [x] Hacer que la pieza de personaje desaparezca cuando este muere.

- [ ] Mejorar toda la parte estetica

- [x] (Opcional) Mostrar una imagen del personaje con el estado actual, en el contenedor de personajes.

- [ ] (Opcional) Hacer que las piezas cambien cuando evoluciona un personaje

- [ ] (Opcional) Hacer que solo se muestren 7 esferas y hacer cumplir la condición de fin de juego

Por ahi se me escapa algo, mencionar de ser asi. Todo esto respecto al juego, creo que falta el informe

**Comment by M-Picco** [comment]
Mostrar algo cuando termina el juego

**Comment by edjus** [comment]
Ya esta la ventana solo falta mejorarlo visualmente.
