### ISSUE TITLE
Ultimo Update

### ISSUE THREAD

**Issue by edjus** [M-Picco/TP2-AlgosIII#2]
Logre avanzar algo de casillero, me parece que hay que corregir lo de como se hace el llenar y vaciar, me parece q no esta bien, es un sugerencia. Para manana hago el diagrama de clases respectivo

**Comment by M-Picco** [comment]
Hola.

Avanzaste bastante, genial. Mañana me levanto y me pongo con tablero.

¿Qué es lo que no te cierra del llenar/vaciar? ¿Que le estás pasando el
ocupante actual? ¿Cómo cambias el estado a desocupado/ocupado?

2017-06-04 1:34 GMT-03:00 edjus <notifications@github.com>:

**Comment by edjus** [comment]
Lo primero seria, no me cierra la idea de que a estado se le pase el ocupante

**Comment by M-Picco** [comment]
Podrías tener la referencia a Casillero sino. ¿Crees que quedría
conceptualmente bien?

Algo por constructor como:

private Casillero casillero;
public CasilleroOcupado(Casillero casillero){
    this.casillero = casillero
}

o por parámetro:

public void Llenar(Casillero casillero, Ubicable nuevoOcupante){
    casillero.setOcupante(nuevoOcupante);
}

Una alternativa nomás.

**Comment by M-Picco** [comment]
Zarpado, pensé que me habías mandado un mail, no que habías abierto un issue en github jajajaja. Al parecer contestando el email podés comentar acá.
