### ISSUE TITLE
Distribucion de los estados de c/personaje 

### ISSUE THREAD

**Issue by kevinspasiuk** [M-Picco/TP2-AlgosIII#4]
Propongo tener un Paquete de cada personaje con el código del mismo y sus respectivos estados para un mayor orden. Qué les parece?

**Comment by M-Picco** [comment]
Yo imaginaba un paquete Personajes y uno Estados

**Comment by Titolasanta** [comment]
y podemos agregar un paquete personaje especifico detro del paquete personaje?

**Comment by M-Picco** [comment]
Creo que sería lo más lógico
