### ISSUE TITLE
Definir mecánica de movimiento

### ISSUE THREAD

**Issue by M-Picco** [M-Picco/TP2-AlgosIII#6]
Creo que la consensuada es click a click. La única duda es el tema de experiencia de usuario.

**Comment by kevinspasiuk** [comment]
click click por ahira y despues por rango

**Comment by M-Picco** [comment]
Ok, lo cierro

**Comment by M-Picco** [comment]
Reabro.

Por turno se puede hacer un movimiento. Si vamos a permitir movimiento a movimiento tendríamos que manejarlo desde el controlador?
