### ISSUE TITLE
Para la segunda entrega

### ISSUE THREAD

**Issue by M-Picco** [M-Picco/TP2-AlgosIII#9]
Mandatorio:

- [x] Transformación de Piccolo y Gohan
- [x] Transformación de Cell
- [x] Ataques especiales sin efectos
- [x] Ataques especiales con efecto (Majin Boo)
- [x] Aumento de daño global para Goku cuando está a 20% o menos de vida

Opcionales:

- [ ] Refactor para añadir clases Ataque, AtaqueEspecial y Movimiento para ser llamadas/usadas desde Estado
- [x] Corregir el código duplicado para ataqueEspecial() en las clases de estado
- [x] Corregir el código duplicado para transformar() en las clases de estado
- [x] Revisar y refactorizar la parte de transformación (ver de aplicar patrón Strategy)

**Comment by M-Picco** [comment]
@kevinspasiuk acá tenés tu bucket list

**Comment by edjus** [comment]
No se dar por valido el ataque especial de Majin Boo, ya que no esta integrado al sistema de turnos
